[package]
name = "takoneko"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
config = "0.14.0"
jsonwebtoken = "9.3.0"
octocrab = "0.38.0"
serde = "1.0.203"
serde_derive = "1.0.203"
tokio = { version = "1", features = ["full"] }
